name: Linux (gcc)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup required packages"
        run: sudo apt-get install -y binutils-dev libssl-dev uuid-dev flex bison ninja-build libboost-all-dev libxxhash-dev libfmt-dev

      - name: "Setup gcc"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Build and test"
        run: |
          mkdir build.debug && cd build.debug
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
          ninja fbe-tests
          ./fbe-tests
